config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  
  get 'file_entries/index'
  get 'file_entries/new'
  get 'file_entries/create'
  get 'file_entries/edit'
  get 'file_entries/update'
  
  delete  '/file_entries/:id/destroy', to: "file_entries#destroy", as: 'file_delete'
  patch '/file_entries/:id/edit', to: "file_entries#edit", as: 'file_edit'
  get 'file_entries/move', to: "file_entries#move"
  get 'file_entries/:id/move', to: "file_entries#move"
  post '/file_entries', to: "file_entries#create"

  patch '/directories/:id/edit', to: "directories#edit", as: 'directory_edit'

  devise_for :users
  
  resources :directories do
    resources :file_entries, shallow: true
    member do
      patch :move
      get :move
    end
  end
  # config/routes.rb
  resources :directories do
    resources :file_entries
  end
  resources :file_entries, only: [:new, :create]

  resources :file_entries do
    member do
      patch :move
    end
  end  
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/directory.rb
class Directory < ApplicationRecord
  belongs_to :user
  has_many :file_entries, dependent: :destroy
  has_many :directories, foreign_key: "parent_id", class_name: "Directory", dependent: :destroy
  belongs_to :parent, class_name: "Directory", optional: true

  validates :name, uniqueness: { scope: :parent_id, message: "already exists in the same parent directory" }

  def ancestors
    parent ? [parent] + parent.ancestors : []
  end

  def descendants
    directories.map do |directory|
      [directory] + directory.descendants
    end.flatten
  end

  def self.all_except(directories)
    directories = Array(directories).flatten
    where.not(id: directories.map(&:id) + directories.map { |d| d.descendants.map(&:id) }.flatten)
  end

  def full_path
    ancestors.reverse.map(&:name).push(name).join('/')
  end

end

app/models/file_entry.rb
class FileEntry < ApplicationRecord
  belongs_to :user
  belongs_to :directory, optional: true
  has_one_attached :file, dependent: :purge
  #  validates :name, uniqueness: { scope: :directory_id, message: "File with this name already exists in the directory" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :file_entries, dependent: :destroy
  has_many :directories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_action :set_directory, only: [:show, :edit, :update, :destroy, :move]
  logger = Rails.logger

  # Wyświetlenie wszystkich folderów urzytkownika
  def index
    @directories = current_user.directories
    Rails.logger.info 'Index view accessed'
  end

  # Wyświetlenie szczegółów folderu
  def show
    @directory = Directory.find(params[:id])
    @subdirectories = @directory.directories
    Rails.logger.info 'Show view accessed'

  end

   # Utworzenie nowego folderu
  def new
    @directory = Directory.new(parent_id: params[:parent_id])
    Rails.logger.info 'New view accessed'

  end

  # Zapisanie nowego folderu do bazy
  def create
    @directory = current_user.directories.new(directory_params)
    if @directory.save
      if @directory.parent
        redirect_to @directory.parent, notice: 'Directory was successfully created.'
      else
        redirect_to root_path, notice: 'Directory was successfully created.'
      end
    Rails.logger.info 'Create view accessed'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  # Aktualizacja właściwości folderu
  def update
    @directory = Directory.find(params[:id])
    original_parent = @directory.parent
    if @directory.update(directory_params)
      if original_parent
        redirect_to original_parent, notice: 'Directory was successfully moved.'
      else
        redirect_to root_path, notice: 'Directory was successfully moved.'
      end
    Rails.logger.info "directory has been updated"

    else
      render :edit, status: :unprocessable_entity
    end
  end

  # Usunięcie folderu z bazy
  def destroy
    @directory = Directory.find(params[:id])
    parent_directory = @directory.parent
    @directory.destroy
    Rails.logger.info "directory has been deleted"
    if parent_directory
      redirect_to parent_directory, notice: 'Directory was successfully deleted.'
    else
      redirect_to root_path, notice: 'Directory was successfully deleted.'
    end
  end

  def move
  end

  private

  def set_directory
    @directory = Directory.find(params[:id])
  end

  def directory_params
    params.require(:directory).permit(:name, :parent_id)
  end

end

app/controllers/file_entries_controller.rb
class FileEntriesController < ApplicationController
  before_action :set_file_entry, only: [:show, :edit, :update, :destroy, :move]
  logger = Rails.logger

  # Wyświetlenie wszystkich plików urzytkownika
  def index
    @file_entries = FileEntry.all
    Rails.logger.info 'Index view accessed'
  end

# Utworzenie nowego pliku
  def new
    @directory = params[:directory_id] ? Directory.find(params[:directory_id]) : nil
    @file_entry = FileEntry.new
    Rails.logger.info 'New view accessed'
  end

# Zapisanie nowego pliku do bazy
  def create
    @directory = params[:directory_id] ? Directory.find(params[:directory_id]) : nil
    @file_entry = @directory ? @directory.file_entries.build(file_params) : FileEntry.new(file_params)
    @file_entry.user = current_user
    
    Rails.logger.info 'Create view accessed'
    if @file_entry.save
      flash[:notice] = 'File was successfully uploaded.'
      redirect_to @directory ? @directory : root_path
    else
      render :new
    end
  end

  def edit
  end


# Aktualizacja właściwości pliku
  def update
    if @file_entry.update(file_entry_params)
      if params[:file_entry][:name].present?
        old_file = @file_entry.file.download
        old_extension = File.extname(@file_entry.file.filename.to_s)
        new_name = params[:file_entry][:name]

        # Append the old extension if the new name doesn't have an extension
        unless File.extname(new_name).present?
          new_name += old_extension
        end

        @file_entry.file.attach(io: StringIO.new(old_file), filename: new_name, content_type: @file_entry.file.content_type)
      end

      Rails.logger.info "file has been updated"
      redirect_to @file_entry.directory ? @file_entry.directory : root_path, notice: 'File entry was successfully updated.'
    else
      render :edit
    end

  end

  # Usunięcie pliku z bazy
  def destroy
    directory = @file_entry.directory
    @file_entry.file.purge
    @file_entry.destroy
    redirect_to directory ? directory : root_path, notice: 'File entry was successfully destroyed.'
    
    Rails.logger.info "file has been deleted"
    redirect_to file_entries_index_path, notice: 'File entry was successfully destroyed.'
  end

  def move
  end
  
  def download
  end

  def share
  end

  private

  def set_file_entry
    @file_entry = FileEntry.find(params[:id])
  end

  def file_entry_params
    params.require(:file_entry).permit(:user_id, :directory_id, :file, :name)
  end

  def file_params
    params.require(:file_entry).permit(:file, :filename)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    if user_signed_in?
      @orphan_directories = current_user.directories.where(parent_id: nil)
      @orphan_files = current_user.file_entries.where(directory_id: nil)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/file_entries_helper.rb
module FileEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/directories/_form.html.erb
<%= form_with(model: directory) do |form| %>
  <% if directory.errors.any?%>
    <div style="color: red" >
      <h1><%= pluralize(directory.errors.count," error") %> prohibited this file from being saved:</h1>
  
      <ul>
        <% directory.errors.each do |error|%>
          <li><%= error.full_message%></li>
          <%end%>
      </ul>
    </div>
  <%end%>

  <div class="field">
      <%= form.label :name%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :parent %>
    <%= form.select :parent_id, Directory.all.collect {|d| [d.name, d.id]}%>
  </div>
  
  <div>
    <%= form.submit "Upload" %>
  </div>
<% end %>

app/views/directories/create.html.erb
<h1>Directories#create</h1>
<p>Find me in app/views/directories/create.html.erb</p>

app/views/directories/destroy.html.erb
<h1>Directories#destroy</h1>
<p>Find me in app/views/directories/destroy.html.erb</p>

app/views/directories/edit.html.erb
<%= form_with(model: @directory, url: directory_path(@directory), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', @directory.parent || directories_path %>

app/views/directories/index.html.erb
<h1>Lista Folderów</h1>
<ul>
  <% @directories.each do |directory| %>
    <li><%= link_to directory.name, directory %></li>
    <%= button_to 'Delete', directory_path(directory), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'rename', directory_edit_path(directory), method: :edit%>
    <%= link_to 'Move', move_directory_path(directory), method: :edit %>
  <% end %>
</ul>
<%= link_to 'Nowy Folder', new_directory_path %>
<%= link_to 'Back', :back %>

app/views/directories/move.html.erb
<%= form_with(model: @directory, url: directory_path(@directory), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :parent %>
    <%= form.select :parent_id, (@directory.parent ? [['Top Level', nil]] : []) + Directory.all_except(@current_parent ? [@directory, @current_parent] : @directory).collect {|d| [d.full_path, d.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', :back %>

app/views/directories/new.html.erb
<%= form_with(model: @directory, local: true) do |form| %>
  <% if @directory.errors.any?%>
    <div style="color: red" >
      <h1><%= pluralize(@directory.errors.count," error") %> prohibited this file from being saved:</h1>

      <ul>
        <% @directory.errors.each do |error|%>
          <li><%= error.full_message%></li>
        <%end%>
      </ul>
    </div>
  <%end%>

  <%= form.hidden_field :parent_id %>
    <%= form.label :name%>
    <%= form.text_field :name %>

  <div>
    <%= form.submit "Stwórz" %>
  </div>
<% end %>
<%= link_to 'Back', @directory.parent_id ? directory_path(@directory.parent_id) : root_path %>

app/views/directories/show.html.erb
<p><h2>Foldery</h2></p>
<% @directory.directories.each do |directory|%>
  <li>
    <%=link_to directory.name,directory%> -
    <%= link_to 'Przenieś', move_directory_path(directory)%> |
    <%= link_to 'Zmień nazwę', edit_directory_path(directory)%> |
    <%= button_to 'Usuń', directory_path(directory), method: :delete, form: {style: 'display:inline-block;'}%>
  </li>
<%end %>
<br>
<%= link_to 'Stwórz folder', new_directory_path(parent_id: @directory.id) %>

<p><h2>Pliki</h2></p>
<% @directory.file_entries.each do |file| %>
  <li>
    <% if file.file.attached? %>
      <%= link_to file.file.filename.to_s, rails_blob_path(file.file, disposition: "attachment") %> -
    <% else %>
      <%= link_to 'No file attached', '#' %>
    <% end %>
    <%= link_to 'Przenieś', move_file_entry_path(file)%> |
    <%= link_to 'Zmień nazwę', edit_file_entry_path(file)%> | 
    <%= button_to 'Usuń', file_entry_path(file), method: :delete, form: {style: 'display:inline-block;'}%>
  </li>
<%end %>
<br><%= link_to 'Załaduj plik', new_file_entry_path(directory_id: @directory.id) %><br><br>
<%= link_to 'Back', @directory.parent.nil? ? root_path : directory_path(@directory.parent) %>

app/views/directories/update.html.erb
<% if @directory.update(directory_params) %>
  <p>directory was successfully updated.</p>
<% else %>
  <p>There was an error updating the directory.</p>
<% end %>

app/views/file_entries/_form.html.erb
<%= form_with(model: [@directory, @file_entry], local: true) do |form| %>
  <% if file_entry.errors.any?%>
    <div style="color: red" >
      <h1><%= pluralize(file_entry.errors.count," error") %> prohibited this file from being saved:</h1>
  
      <ul>
        <% file_entry.errors.each do |error|%>
          <li><%= error.full_message%></li>
          <%end%>
      </ul>
    </div>
  <%end%>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.submit "Upload" %>
  </div>
<% end %>

app/views/file_entries/create.html.erb
<h1>FileEntries#create</h1>
<p>Find me in app/views/file_entries/create.html.erb</p>

app/views/file_entries/destroy.html.erb
<h1>FileEntries#destroy</h1>
<p>Find me in app/views/file_entries/destroy.html.erb</p>

app/views/file_entries/download.html.erb
<h1>FileEntries#download</h1>
<p>Find me in app/views/file_entries/download.html.erb</p>

app/views/file_entries/edit.html.erb
<!-- app/views/file_entries/edit.html.erb -->
<%= form_with(model: @file_entry, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', @file_entry.directory ? directory_path(@file_entry.directory) : root_path %>

app/views/file_entries/index.html.erb
<h1>Lista Plików</h1>
<ul>
  <% @file_entries.each do |file_entry| %>
    <li>
    <%= link_to file_entry.file.filename, file_entry %>
    <%= button_to 'Delete', file_delete_path(file_entry), method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'rename', file_edit_path(file_entry), method: :edit%>
    <%= link_to 'move', move_file_entry_path(file_entry), method: :edit%>
    </li>
  <% end %>
</ul>
<%= link_to 'Nowy Plik', new_file_entry_path %>
<%= link_to 'Back', root_path %>

app/views/file_entries/move.html.erb
<%= form_with(model: @file_entry, url: file_entry_path(@file_entry), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :directory %>
    <%= form.select :directory_id, (@file_entry.directory ? [['Top Level', nil]] : []) + Directory.all.reject { |d| d == @file_entry.directory }.collect { |d| [d.full_path, d.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', @file_entry.directory ? directory_path(@file_entry.directory) : root_path %>

app/views/file_entries/new.html.erb
<%= form_with(model: [@directory, @file_entry], local: true) do |form| %>
  <% if @file_entry.errors.any?%>
    <div style="color: red" >
      <h1><%= pluralize(@file_entry.errors.count," error") %> prohibited this file from being saved:</h1>

      <ul>
        <% @file_entry.errors.each do |error|%>
          <li><%= error.full_message%></li>
        <%end%>
      </ul>
    </div>
  <%end%>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.submit "Upload" %>
  </div>
<% end %>

<%= link_to 'Back', @directory ? directory_path(@directory) : root_path %>

app/views/file_entries/share.html.erb
<h1>FileEntries#share</h1>
<p>Find me in app/views/file_entries/share.html.erb</p>

app/views/file_entries/show.html.erb
<% if @file_entry.file.attached?%>
        <%= link_to @file_entry.file.filename, url_for(@file_entry.file) %>
    <div>
        <%if @file_entry.file.image?%>
            <%= image_tag(@file_entry.file)%>
        <% elsif @file_entry.file.video?%>
            <%= video_tag(url_for(@file_entry.file), controls: "")%>
        <% end%>
    </div>
    <%= link_to 'Back', file_entries_path %>
<%end%>

app/views/file_entries/update.html.erb
<% if @file_entry.update(file_entry_params) %>
  <p>File entry was successfully updated.</p>
<% else %>
  <p>There was an error updating the file entry.</p>
<% end %>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<% if user_signed_in? %>
  <h1>Witaj <%= current_user.email %>!</h1>
  <h2>Foldery</h2>
  <ul>
    <% @orphan_directories.each do |directory| %>
      <li>
        <%= link_to directory.name, directory_path(directory) %> -
        <%= link_to 'Przenieś', move_directory_path(directory)%> |
        <%= link_to 'Zmień nazwę', edit_directory_path(directory)%> |
        <%= button_to 'Usuń', directory_path(directory), method: :delete, form: {style: 'display:inline-block;'}%>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Stwórz folder', new_directory_path%>
  <h2>Pliki</h2>
  <ul>
    <% @orphan_files.each do |file| %>
      <li>
        <% if file.file.attached? %>
          <%= link_to file.file.filename.to_s, rails_blob_path(file.file, disposition: "attachment") %> -
        <% else %>
          <%= link_to 'No file attached', '#' %>
        <% end %>
        <%= link_to 'Przenieś', move_file_entry_path(file)%> |
        <%= link_to 'Zmień nazwę', edit_file_entry_path(file)%> |
        <%= button_to 'Usuń', file_entry_path(file), method: :delete, form: {style: 'display:inline-block;'}%>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Załaduj plik', @directory ? new_directory_file_entry_path(@directory) : new_file_entry_path %> <br><br>
  <%= link_to 'Wyloguj się', destroy_user_session_path, method: :delete %>
<% else %>
  <h1>Witaj w aplikacji Magazyn Plików!</h1>
  <%= link_to 'Zaloguj się', new_user_session_path %> lub
  <%= link_to 'Zarejestruj się', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EDisk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if @directory %>
    <p>Current path: <%= @directory.full_path %></p>
  <% end %>
    <%= yield %>
  </body>
</html>